### ISSUE TITLE
Invalid parse mode "html"

### ISSUE THREAD

**Issue by gdsday** [KangersHub/TorrentLeechX#30]
```2022-05-11T03:46:39.580169+00:00 app[worker.1]: 11-May-22 09:16:39 - INFO - @hrkbleebot Has Started Running...🏃💨💨 [__main__.py:282]
2022-05-11T03:47:20.576993+00:00 app[worker.1]: 11-May-22 09:17:20 - ERROR - Invalid parse mode "html" [dispatcher.py:253]
2022-05-11T03:47:20.577002+00:00 app[worker.1]: Traceback (most recent call last):
2022-05-11T03:47:20.577003+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
2022-05-11T03:47:20.577004+00:00 app[worker.1]:     await handler.callback(self.client, *args)
2022-05-11T03:47:20.577004+00:00 app[worker.1]:   File "/app/tobrot/plugins/incoming_message_fn.py", line 58, in incoming_message_f
2022-05-11T03:47:20.577005+00:00 app[worker.1]:     credit = await message.reply_text(
2022-05-11T03:47:20.577005+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/pyrogram/types/messages_and_media/message.py", line 959, in reply_text
2022-05-11T03:47:20.577006+00:00 app[worker.1]:     return await self._client.send_message(
2022-05-11T03:47:20.577006+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/messages/send_message.py", line 122, in send_message
2022-05-11T03:47:20.577006+00:00 app[worker.1]:     message, entities = (await utils.parse_text_entities(self, text, parse_mode, entities)).values()
2022-05-11T03:47:20.577007+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/pyrogram/utils.py", line 343, in parse_text_entities
2022-05-11T03:47:20.577007+00:00 app[worker.1]:     text, entities = (await client.parser.parse(text, parse_mode)).values()
2022-05-11T03:47:20.577008+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/pyrogram/parser/parser.py", line 54, in parse
2022-05-11T03:47:20.577008+00:00 app[worker.1]:     raise ValueError(f'Invalid parse mode "{mode}"')
2022-05-11T03:47:20.577009+00:00 app[worker.1]: ValueError: Invalid parse mode "html"```
Am i did something wrong?

**Comment by mr-wh1tehat** [comment]
> ```
> 2022-05-11T03:47:20.576993+00:00 app[worker.1]: 11-May-22 09:17:20 - ERROR - Invalid parse mode "html" [dispatcher.py:253]
> 2022-05-11T03:47:20.577002+00:00 app[worker.1]: Traceback (most recent call last):
> 2022-05-11T03:47:20.577003+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
> 2022-05-11T03:47:20.577004+00:00 app[worker.1]:     await handler.callback(self.client, *args)
> 2022-05-11T03:47:20.577004+00:00 app[worker.1]:   File "/app/tobrot/plugins/incoming_message_fn.py", line 58, in incoming_message_f
> 2022-05-11T03:47:20.577005+00:00 app[worker.1]:     credit = await message.reply_text(
> 2022-05-11T03:47:20.577005+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/pyrogram/types/messages_and_media/message.py", line 959, in reply_text
> 2022-05-11T03:47:20.577006+00:00 app[worker.1]:     return await self._client.send_message(
> 2022-05-11T03:47:20.577006+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/messages/send_message.py", line 122, in send_message
> 2022-05-11T03:47:20.577006+00:00 app[worker.1]:     message, entities = (await utils.parse_text_entities(self, text, parse_mode, entities)).values()
> 2022-05-11T03:47:20.577007+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/pyrogram/utils.py", line 343, in parse_text_entities
> 2022-05-11T03:47:20.577007+00:00 app[worker.1]:     text, entities = (await client.parser.parse(text, parse_mode)).values()
> 2022-05-11T03:47:20.577008+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/pyrogram/parser/parser.py", line 54, in parse
> 2022-05-11T03:47:20.577008+00:00 app[worker.1]:     raise ValueError(f'Invalid parse mode "{mode}"')
> 2022-05-11T03:47:20.577009+00:00 app[worker.1]: ValueError: Invalid parse mode "html"```
> did i do something wrong?
> ```

set pyrogram version to ==1.4.16
